### ISSUE TITLE
Music Box Part Doesn't Work With Noctis

### ISSUE THREAD

**Issue by BlakeBoxberger** [DGh0st/HideCCSwitchBackground#2]
Title. Someone reported it to me. I don't have Noctis, so I can't test it but I thought I'd let you know.
-NZ9

**Comment by DGh0st** [comment]
[0bfc9f7](https://github.com/DGh0st/HideCCSwitchBackground/commit/0bfc9f732c675f40a1094c8ce7cd58665a3e2ac0) should fix it.

If you want to add it to your tweak, [this specifically](https://github.com/DGh0st/HideCCSwitchBackground/commit/0bfc9f732c675f40a1094c8ce7cd58665a3e2ac0#diff-cbd956fbbf6228e5301b4b4a11af1061R173) should fix it for Noctis. You don't need to change your other hook that was just me trying stuff.

**Comment by BlakeBoxberger** [comment]
Cool, thank you so much!
